#!/usr/bin/env sh

source "$CONFIG_DIR/variables.sh"

sketchybar --bar height=$BAR_HEIGHT \
	color=$BAR_COLOR \
	position=top \
	sticky=on \
	padding_right=18 \
	padding_left=18 \
	corner_radius=0 \
	y_offset=0 \
	margin=0 \
	blur_radius=0

sketchybar --default updates=when_shown \
	label.font="$FONT:Medium:14.0" \
	label.color="$LABEL_COLOR" \
	icon.font.size=16

# Left
source "$ITEMS_DIR/spaces.sh"

# Right
source "$ITEMS_DIR/clock.sh"
source "$ITEMS_DIR/volume.sh"
source "$ITEMS_DIR/battery.sh"

# Force all scripts to run the first time (never do this in a script)
sketchybar --update
